spring.application.name=server
spring.data.mongodb.uri=mongodb+srv://parasbhardwaj707_db_user:JRQ2Q5OmvHXUUuqn@cluster0.f5hcom7.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=gymmers
server.port=8080
jwt.secret=gymmers_secret_key_must_be_very_long_and_secure_123456
jwt.expiration=86400000
